"""last seen field for users

Revision ID: e88b5cfcd80d
Revises: 7cdedfa2fed6
Create Date: 2025-02-07 11:43:21.462239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy import update
from bot.db.models import User
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = 'e88b5cfcd80d'
down_revision: Union[str, None] = '7cdedfa2fed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    session = Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.Date(), nullable=True))

    session.execute(
        update(User)
        .values(last_seen = datetime.today().date())
        .where(User.last_seen == None)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
